// Code generated by protoc-gen-go.
// source: api/services/uinames/uinames.proto
// DO NOT EDIT!

/*
Package uinames is a generated protocol buffer package.

It is generated from these files:
	api/services/uinames/uinames.proto

It has these top-level messages:
	GetNameRequest
	GetNameResponse
*/
package uinames

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetNameRequest struct {
}

func (m *GetNameRequest) Reset()                    { *m = GetNameRequest{} }
func (m *GetNameRequest) String() string            { return proto.CompactTextString(m) }
func (*GetNameRequest) ProtoMessage()               {}
func (*GetNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetNameResponse struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Surname string `protobuf:"bytes,2,opt,name=surname" json:"surname,omitempty"`
	Gender  string `protobuf:"bytes,3,opt,name=gender" json:"gender,omitempty"`
	Region  string `protobuf:"bytes,4,opt,name=region" json:"region,omitempty"`
}

func (m *GetNameResponse) Reset()                    { *m = GetNameResponse{} }
func (m *GetNameResponse) String() string            { return proto.CompactTextString(m) }
func (*GetNameResponse) ProtoMessage()               {}
func (*GetNameResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetNameResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetNameResponse) GetSurname() string {
	if m != nil {
		return m.Surname
	}
	return ""
}

func (m *GetNameResponse) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *GetNameResponse) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func init() {
	proto.RegisterType((*GetNameRequest)(nil), "GetNameRequest")
	proto.RegisterType((*GetNameResponse)(nil), "GetNameResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Uinames service

type UinamesClient interface {
	GetName(ctx context.Context, in *GetNameRequest, opts ...grpc.CallOption) (*GetNameResponse, error)
}

type uinamesClient struct {
	cc *grpc.ClientConn
}

func NewUinamesClient(cc *grpc.ClientConn) UinamesClient {
	return &uinamesClient{cc}
}

func (c *uinamesClient) GetName(ctx context.Context, in *GetNameRequest, opts ...grpc.CallOption) (*GetNameResponse, error) {
	out := new(GetNameResponse)
	err := grpc.Invoke(ctx, "/Uinames/GetName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Uinames service

type UinamesServer interface {
	GetName(context.Context, *GetNameRequest) (*GetNameResponse, error)
}

func RegisterUinamesServer(s *grpc.Server, srv UinamesServer) {
	s.RegisterService(&_Uinames_serviceDesc, srv)
}

func _Uinames_GetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UinamesServer).GetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Uinames/GetName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UinamesServer).GetName(ctx, req.(*GetNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Uinames_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Uinames",
	HandlerType: (*UinamesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetName",
			Handler:    _Uinames_GetName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/services/uinames/uinames.proto",
}

func init() { proto.RegisterFile("api/services/uinames/uinames.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 170 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4a, 0x2c, 0xc8, 0xd4,
	0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x2d, 0xd6, 0x2f, 0xcd, 0xcc, 0x4b, 0xcc, 0x45, 0xd0,
	0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x4a, 0x02, 0x5c, 0x7c, 0xee, 0xa9, 0x25, 0x7e, 0x89, 0xb9,
	0xa9, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x4a, 0xf9, 0x5c, 0xfc, 0x70, 0x91, 0xe2, 0x82,
	0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x21, 0x2e, 0x16, 0x90, 0x1e, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x30, 0x5b, 0x48, 0x82, 0x8b, 0xbd, 0xb8, 0xb4, 0x08, 0x2c, 0xcc, 0x04, 0x16, 0x86, 0x71,
	0x85, 0xc4, 0xb8, 0xd8, 0xd2, 0x53, 0xf3, 0x52, 0x52, 0x8b, 0x24, 0x98, 0xc1, 0x12, 0x50, 0x1e,
	0x48, 0xbc, 0x28, 0x35, 0x3d, 0x33, 0x3f, 0x4f, 0x82, 0x05, 0x22, 0x0e, 0xe1, 0x19, 0x59, 0x72,
	0xb1, 0x87, 0x42, 0xdc, 0x24, 0xa4, 0xc7, 0xc5, 0x0e, 0xb5, 0x5b, 0x88, 0x5f, 0x0f, 0xd5, 0x5d,
	0x52, 0x02, 0x7a, 0x68, 0xce, 0x52, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xc2, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x49, 0x50, 0x41, 0x03, 0xea, 0x00, 0x00, 0x00,
}
